### ISSUE TITLE
triangle counting -- where are Gunrock results?

### ISSUE THREAD

**Issue by jowens** [eunaeuna/GraphFrameworkOnGPUs#15]
I understand @neoblizz sent an email several weeks ago that indicated how you could use Gunrock to get TC results. It was in `dev` branch, if I recall. (It is currently in the `master` branch, https://github.com/gunrock/gunrock/tree/master/gunrock/app/tc .) Where are the Gunrock TC results?

**Comment by ogreen** [comment]
Is this is the same as issue #6 ?

**Comment by jowens** [comment]
Copied into #6.
